import { Bike } from "./types";

export const IDR_TO_USD = 16000;

export const BIKES: Bike[] = [
  {
    id: "honda-scoopy",
    name: "Honda Scoopy",
    type: ["Popular", "Beginner", "Retro"],
    engineSize: 110,
    bestFor: ["City", "Photo"],
    hasABS: false,
    hasBigTrunk: false,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 50000,
    priceWeekly: 40000,
    priceMonthly: 26000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Beginner Friendly: Most popular choice for girls and first-time riders, best for photo",
    features: ["USB charger", "lightweight", "retro"]
  },
  {
    id: "yamaha-nmax",
    name: "Yamaha NMAX",
    type: ["Popular", "Maxi"],
    engineSize: 155,
    bestFor: ["City", "Long Trip"],
    hasABS: true,
    hasBigTrunk: true,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 140000,
    priceWeekly: 130000,
    priceMonthly: 65000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "All-rounder: Perfect balance of power and comfort for any distance.",
    features: ["ABS", "Large trunk", "Keyless", "LED"]
  },
  {
    id: "honda-vario-125",
    name: "Honda Vario 125",
    type: "Budget",
    engineSize: 125,
    bestFor: ["City"],
    hasABS: false,
    hasBigTrunk: false,
    hasPhoneHolder: true,
    hasUSB: false,
    pricePerDay: 50000,
    priceWeekly: 50000,
    priceMonthly: 30000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Economy Choice: Simple, reliable, and great for daily short commutes.",
    features: ["Flat floor for bags", "agile"]
  },
  {
    id: "honda-vario-160",
    name: "Honda Vario 160",
    type: "Popular",
    engineSize: 160,
    bestFor: ["City"],
    hasABS: true,
    hasBigTrunk: false,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 60000,
    priceWeekly: 60000,
    priceMonthly: 40000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Fast City Move: Powerful engine in a compact body for heavy traffic.",
    features: ["ABS", "Disc brakes", "high power"]
  },
  {
    id: "honda-pcx",
    name: "Honda PCX",
    type: ["Popular", "Maxi"],
    engineSize: 160,
    bestFor: ["City", "Long Trip"],
    hasABS: true,
    hasBigTrunk: true,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 140000,
    priceWeekly: 125000,
    priceMonthly: 70000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Smooth Cruiser: For those who prefer a \"softer\" and more prestigious ride.",
    features: ["ABS", "Large fuel tank", "premium comfort"]
  },
  {
    id: "yamaha-aerox",
    name: "Yamaha Aerox",
    type: "Popular",
    engineSize: 155,
    bestFor: ["City"],
    hasABS: true,
    hasBigTrunk: false,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 140000,
    priceWeekly: 135000,
    priceMonthly: 85000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Active Riders: Sporty feel and great stability in corners.",
    features: ["ABS", "Sporty look", "wide tires"]
  },
  {
    id: "vespa-sprint",
    name: "Vespa Sprint",
    type: "Retro",
    engineSize: 150,
    bestFor: ["City", "Photo"],
    hasABS: true,
    hasBigTrunk: false,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 250000,
    priceWeekly: 225000,
    priceMonthly: 145000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Lifestyle & Style: Perfect for Canggu/Seminyak vibes and city cruising.",
    features: ["ABS", "Steel body", "status", "Italian style"]
  },
  {
    id: "honda-adv",
    name: "Honda ADV",
    type: "Maxi",
    engineSize: 160,
    bestFor: ["Long Trip", "Mountains"],
    hasABS: true,
    hasBigTrunk: true,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 170000,
    priceWeekly: 155000,
    priceMonthly: 70000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Explorer: Best for mountains (Bedugul/Kintamani) and bumpy roads.",
    features: ["ABS", "Crossover suspension", "smooth ride"]
  },
  {
    id: "yamaha-xmax",
    name: "Yamaha XMAX",
    type: "Maxi",
    engineSize: 250,
    bestFor: ["Long Trip", "Mountains"],
    hasABS: true,
    hasBigTrunk: true,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 250000,
    priceWeekly: 240000,
    priceMonthly: 155000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Premium Touring: Long island trips and maximum highway comfort.",
    features: ["ABS", "Fits 2 helmets", "Traction Control"]
  },
  {
    id: "honda-beat",
    name: "Honda Beat",
    type: ["Budget", "Beginner"],
    engineSize: 110,
    bestFor: ["City"],
    hasABS: false,
    hasBigTrunk: false,
    hasPhoneHolder: true,
    hasUSB: false,
    pricePerDay: 65000,
    priceWeekly: 55000,
    priceMonthly: 35000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Budget/Pro: Best for navigating the narrowest \"gangs\" (small streets).",
    features: ["Narrowest body", "fuel efficient"]
  },
  {
    id: "honda-genio",
    name: "Honda Genio",
    type: ["Budget", "Beginner"],
    engineSize: 110,
    bestFor: ["City"],
    hasABS: false,
    hasBigTrunk: false,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 75000,
    priceWeekly: 65000,
    priceMonthly: 40000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Easy City Ride: A stylish and slightly more modern alternative to Scoopy.",
    features: ["Next-gen frame", "easy for beginners"]
  },
  {
    id: "yamaha-fazzio",
    name: "Yamaha Fazzio",
    type: ["Beginner", "Retro"],
    engineSize: 125,
    bestFor: ["City", "Photo"],
    hasABS: false,
    hasBigTrunk: false,
    hasPhoneHolder: true,
    hasUSB: false,
    pricePerDay: 50000,
    priceWeekly: 45000,
    priceMonthly: 30000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Trendsetter: Stylish, modern, and very easy to ride for beginners.",
    features: ["Hybrid engine", "stylish design"]
  },
  {
    id: "yamaha-gear",
    name: "Yamaha Gear",
    type: "Budget",
    engineSize: 125,
    bestFor: ["City"],
    hasABS: false,
    hasBigTrunk: false,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 80000,
    priceWeekly: 70000,
    priceMonthly: 50000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Urban Utility: Great for carrying grocery bags or surf racks.",
    features: ["Kids/Cargo footrests", "durable"]
  },
  {
    id: "yamaha-lexi",
    name: "Yamaha Lexi",
    type: "Maxi",
    engineSize: 155,
    bestFor: ["City"],
    hasABS: false,
    hasBigTrunk: false,
    hasPhoneHolder: true,
    hasUSB: true,
    pricePerDay: 120000,
    priceWeekly: 105000,
    priceMonthly: 60000,
    image: "https://images.unsplash.com/photo-1558981403-c5f91cbba527?auto=format&fit=crop&q=80&w=800",
    description: "Comfort Economy: A lighter alternative to NMAX with easy step-through.",
    features: ["Flat floor", "wide seat"]
  }
];
